OPENAI_API_KEY = "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"
OPENAI_ORG = "org-SeObmBLbe1IQc2WcEy9YKmWM"
OPENAI_PROJECT = "proj_uztbJMxn3MXJ3fdKtAe0UzWk"
