OPENAI_API_KEY = "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"
OPENAI_ORG = "org-SeObmBLbe1IQc2WcEy9YKmWM"
OPENAI_PROJECT = "proj_uztbJMxn3MXJ3fdKtAe0UzWk"
