OPENAI_API_KEY = "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"
OPENAI_ORG = "org-SeObmBLbe1IQc2WcEy9YKmWM"
OPENAI_PROJECT = "proj_tlNs2jetTQqqqj3bM8diilxS"
