OPENAI_API_KEY = "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"
OPENAI_ORG = "org-SeObmBLbe1IQc2WcEy9YKmWM"
OPENAI_PROJECT = "proj_tlNs2jetTQqqqj3bM8diilxS"
